# Generated by Django 3.2.3 on 2021-06-08 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20210608_1437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='poster',
        ),
    ]
